// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzuclmbfdhnwtdppwcul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6dWNsbWJmZGhud3RkcHB3Y3VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2NzE4MDksImV4cCI6MjA4OTI0NzgwOX0.gIieBsvNzu9KKapBF3o0uyBGhY185FwwoQDF37H0jY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});